### ISSUE TITLE
Add tsconfig.json

### ISSUE THREAD

**Issue by cbowdon** [cbowdon/TsMonad#16]
- Keep the codebase up to date
- Enable TIDE (Emacs package)
- Must check whether it conflicts with grunt-typescript or makes some parts of grunt-typescript redundant

**Comment by cbowdon** [comment]
Done (superseded) by changes from @aitoroses, if he doesn't mind me merging in his fork?

**Comment by aitoroses** [comment]
Hi @cbowdon, I see that's already merged! You can close the issue then 😄
