### ISSUE TITLE
support DefinitlyTyped

### ISSUE THREAD

**Issue by ValentinTrinque** [cbowdon/TsMonad#2]
Hello !

It would be great to support [DefinitlyTyped](http://definitelytyped.org) here. It would make it easier for Typescript coders to access to your library by avoiding unnecessary paper work.

Here is the link for contribution:
http://definitelytyped.org/guides/contributing.html

Is it possible ?

**Comment by cbowdon** [comment]
You're quite right, it would be a good thing and I will do so when I find time. If you would prefer to make the contribution to DT yourself so it happens a bit more quickly, no problem.

**Comment by ValentinTrinque** [comment]
Ok. I fork it and I am working on the definition file.

[Here is the work-in-progress](https://github.com/ValentinTrinque/TsMonad/blob/dt-support/dist/tsmonad.d.ts)

Come back to you ASAP

**Comment by ValentinTrinque** [comment]
WIP: https://github.com/borisyankov/DefinitelyTyped/pull/4677

**Comment by ValentinTrinque** [comment]
It's aliiiive ! => https://github.com/borisyankov/DefinitelyTyped/pull/4677#issuecomment-113999501

You can just run this commad. It will search for tsmonad, install it and save it to the tsd file.
`tsd query tsmonad -a install -s`

**Comment by cbowdon** [comment]
Awesome! Thanks Valentin
