### ISSUE TITLE
Exported external package typings file is not a module

### ISSUE THREAD

**Issue by denis-sokolov** [cbowdon/TsMonad#20]
Trying to use the new tsmonad version results in this message when compiling my project:

> Exported external package typings file '.../node_modules/tsmonad/dist/tsmonad.d.ts' is not a module.
> Please contact the package author to update the package definition.

Commit 6494304 was wrong, as [TypeScript docs](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) clearly show the definition files should be written as external modules.

**Comment by chromeragnarok** [comment]
+1

**Comment by dalealleshouse** [comment]
+1

**Comment by denis-sokolov** [comment]
@chromeragnarok, @dalealleshouse, I bring your attention that you can now add your support for the issue [using a reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

**Comment by rparree** [comment]
I am trying to use this within an angular2  application (using webpack). Is there a work around for this issue?

tx.,

**Comment by cbowdon** [comment]
Apologies everyone for the delay in getting to this! I've been offline for some time. Thank you for raising it, I'll see what I can do.

**Comment by cbowdon** [comment]
Ok, 0.6.1 is up on NPM. Removed the typings thing. Surprised that the definitions file generated by `tsc` is not by default an acceptable typings file.

**Comment by denis-sokolov** [comment]
0.6.1 fixes my problem!

To get the typings I use a manual `/// <reference path="./node_modules/tsmonad/dist/tsmonad.d.ts" />`
