### ISSUE TITLE
Maybe .valueOrThrow typings are not in dist/tsmonad.d.ts

### ISSUE THREAD

**Issue by denis-sokolov** [cbowdon/TsMonad#22]
Typings for `.valueOrThrow` are not available in 0.6.1 `dist/`. A patch would be appreciated.

**Comment by cbowdon** [comment]
That's intentional - I only bothered to fix the immediate issue. I'll push an update shortly.

**Comment by cbowdon** [comment]
Sorry Denis, I haven't had much time to work on this. I will try and get round to it soon. Thanks for your continued contributions!

**Comment by cbowdon** [comment]
Ok, fixed in 0.7+. (Let me know if wrong.)
