### ISSUE TITLE
0.7.0 is not published on npm public registry

### ISSUE THREAD

**Issue by thomasguillory** [cbowdon/TsMonad#24]
Last version on npm public registry is 0.6.1: https://www.npmjs.com/package/tsmonad
However there is a version 0.7.0 on github: https://github.com/cbowdon/TsMonad/releases/tag/v0.7.0

Do you plan to publish it soon ?

**Comment by jgrenat** [comment]
Is there something preventing v0.7.0 to be published into npm that we can help with?

**Comment by davnn** [comment]
Only the version number changed from 0.6.1 to 0.7.0, but maybe we have found a good reason to implement automatic publishing to npm?

**Comment by Offirmo** [comment]
@cbowdon please `npm publish`

**Comment by cbowdon** [comment]
Sorry folks, this is just a case of me not being available to work on the code (a situation that is set to continue). At the time I was holding off because IIRC the 0.7 release included a large-ish PR. I'll try and review and publish as soon as I can.

**Comment by cbowdon** [comment]
Published!
