### ISSUE TITLE
Restructure to export specific modules 

### ISSUE THREAD

**Issue by watzon** [cbowdon/TsMonad#26]
This is a great library first off. My only qualm is that in order to import it I have to use the outdated `/// <reference_path ... />`. Ideally this library should be findable by the typescript compiler by having an `index.d.ts` file in the root directory. Modules should also ideally be importable by using `import { Module } from 'tsmonad`. If you'd like I can submit a PR

**Comment by cbowdon** [comment]
Thanks, that is a really good idea. A PR would be welcome as I am currently not able to spend much time on this project.

**Comment by cbowdon** [comment]
Sorry, I have no time to look into this. Please reopen if it's a concern.
