### ISSUE TITLE
Maybe.contains?

### ISSUE THREAD

**Issue by emmanueltouzery** [cbowdon/TsMonad#27]
would you accept a pull request for Maybe.contains?

    Maybe<T>.contains(value: T): boolean

**Comment by cbowdon** [comment]
I would! But I'm afraid I am not currently able to spend much time on my OSS stuff so it may take some time before it filtered through to npm.

**Comment by emmanueltouzery** [comment]
actually fell back to using monet.js for now... saw other things there which suited me better. closing this for now then.
