### ISSUE TITLE
Loading time seems a little high

### ISSUE THREAD

**Issue by Ptival** [cbowdon/TsMonad#30]
Hello,

I was looking through the loading times of different libraries I use to figure out who slows everything down.

I expected TsMonad to be among the lowest ones, it turned out to be the among the second highest ones.

When I require `tsmonad`, it takes ~100ms.

For comparison, I get times like those:

```
ace: 500ms
bootstrap: 50ms
bluebird: 100ms
jquery: 100ms
jss: 20ms
lodash: 60ms
MathJax: 40ms
rx: 60ms
tsmonad: 100ms
w2ui: 80ms
```

**Comment by cbowdon** [comment]
That is a big surprise, as it has no dependencies at all. Thanks for raising this, I'll see if I can reproduce it and if so do something about it.

**Comment by cbowdon** [comment]
Sorry, I have no time to look into this. Please reopen if it's a concern.
