### ISSUE TITLE
Type file is missing in 0.7.1

### ISSUE THREAD

**Issue by iamwilhelm** [cbowdon/TsMonad#35]
I installed 0.7.1, and it complained that it couldn't find the type file for tsmonad. I installed 0.7.0, and it worked. 

With 0.7.1, when I looked in "node_modules/tsmonad/dist/tsmonad.d.ts", I didn't see a tsmonad.d.ts.

**Comment by cbowdon** [comment]
Thanks for raising this. Probably related to the extra typings section I mistakenly merged in recently. Will push 0.7.2 shortly.

**Comment by cbowdon** [comment]
Ok, 0.7.2 is up. Is that working for you?

**Comment by iamwilhelm** [comment]
Yup, it is, thanks! 💯

**Comment by russelldmatt** [comment]
This is likely user error as I'm new to typescript, but I'm having the same issue with 0.8.0.  As a sanity check, I installed 0.7.2, but even with that version I still don't see the tsmonad.d.ts file.  

With latest (0.8.0):
```bash
Matts-MacBook-Pro-3:typescript russell$ npm install tsmonad
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ tsmonad@0.8.0
added 1 package in 0.626s
Matts-MacBook-Pro-3:typescript russell$ tree node_modules/
node_modules/
└── tsmonad
    ├── LICENSE-MIT
    ├── README.md
    ├── dist
    │   ├── tsmonad.js
    │   └── tsmonad.js.map
    ├── lib
    │   └── src
    │       ├── either.d.ts
    │       ├── index.d.ts
    │       ├── maybe.d.ts
    │       ├── monad.d.ts
    │       └── writer.d.ts
    └── package.json

4 directories, 10 files
```

Any help would be appreciated, thanks!
