### ISSUE TITLE
Validation type

### ISSUE THREAD

**Issue by OliverJAsh** [cbowdon/TsMonad#36]
Hi there,

Do you have any plans to add a `Validation` type?

As far as I understand, this type is not a monad but instead an applicative functor, which means it is useful for aggregation of failures—which is harder to achieve with a monad like `Either`. I'm probably wrong, though :-) Reference: http://robotlolita.me/2013/12/08/a-monad-in-practicality-first-class-failures.html

Would be great to hear your thoughts, and thanks for the great library!

Oliver

**Comment by cbowdon** [comment]
This is a nice idea. I don't have any plans myself (you have given me some interesting reading to do) but I would welcome any PRs.

**Comment by cbowdon** [comment]
Sorry, I have no time to look into this. Please reopen if it's a concern.
