### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by ahstro** [cbowdon/TsMonad#43]
Might be a great idea to [keep a changelog](http://keepachangelog.com/)? Trying to figure out what changed between 0.7.2 and 0.8.0 but I have no idea.

**Comment by ahstro** [comment]
(Figured it out with https://github.com/cbowdon/TsMonad/compare/0.7.2...0.8.0, but still, worth keeping one anyway :))

**Comment by cbowdon** [comment]
Good call! I normally put something in the tag (see https://github.com/cbowdon/TsMonad/releases) but didn't for 0.8.0 for some reason. I'll make sure not to forget next time.
