### ISSUE TITLE
npm package is broken because it doesn't include dist/

### ISSUE THREAD

**Issue by mwiencek** [cbowdon/TsMonad#6]
The npm package is currently broken because it doesn't include the dist/ folder: http://registry.npmjs.org/tsmonad/-/tsmonad-0.3.2.tgz

``` bash
$ node
> var TsMonad = require('tsmonad');
Error: Cannot find module 'tsmonad'
```

**Comment by cbowdon** [comment]
Damn, thank you. Fix shortly. Obviously in the interim you can grab the source from here.

**Comment by cbowdon** [comment]
Ok, give npm install tsmonad@0.3.7 a whirl - as far as I can see that resolves it. Let me know if there's anything else. Thanks for raising this.

**Comment by mwiencek** [comment]
Yup, it's working now, thanks! :)
